In [1]:
import pandas as pd
import numpy as np
from scipy import io
import scipy.io


# Set the current working directory
import os
os.chdir(r"C:/Users/Yoshi/Documents/GitHub/flow_around_cylinder/RUN_team_saipan_flow_around_cylinder_SHORTENED_TRIMMED_200_timesteps/postprocessing/")


In [20]:
# Define the number of time steps and variables
num_time_steps = 149
time_step_size = 149
start_time_step = 51

# Initialize lists to store data for each variable
points_data = []
u_data = []
p_data = []


# Create t array starting from the 50th time step
t = np.arange(start_time_step * time_step_size, (start_time_step + num_time_steps) * time_step_size, time_step_size).reshape(-1, 1)

# Load data from CSV files starting from the 50th time step
for timestep in range(start_time_step, start_time_step + num_time_steps):
    filename = f"extract_{timestep}.csv"
    df = pd.read_csv(filename)  # Load CSV into DataFrame
    points_data.append(df[['Points:0', 'Points:1']].values)  # Extract points data
    u_data.append(df[['U:0','U:1']].values)  # Extract velocity data
    p_data.append(df['p'].values)  # Extract pressure data

# Convert data to NumPy arrays
points_data = np.array(points_data).transpose(1, 2, 0)  # Transpose points_data
sliced_points_data = points_data[:, :, 0]
u_data = np.array(u_data).transpose(1, 2, 0)  # Transpose u_data
p_data = np.array(p_data).T

# Create a dictionary to store the data
data_cube = {
    'X_star': sliced_points_data,
    't': t,
    'U_star': u_data,
    'p_star': p_data
}

# Save data as .mat file
io.savemat('data_cube_shortened_200_TRIMMED.mat', data_cube)


In [11]:
sliced_points_data.shape #Shape is (23768, 2, 100)

(8990, 2)

In [15]:
data = scipy.io.loadmat(r"C:/Users/Yoshi/Documents/GitHub/flow_around_cylinder/RUN_team_saipan_flow_around_cylinder_SHORTENED_TRIMMED_200_timesteps/postprocessing/data_cube_shortened_200_TRIMMED.mat")
print(data.keys())




dict_keys(['__header__', '__version__', '__globals__', 'X_star', 't', 'U_star', 'p_star'])


In [16]:
X_star = data['X_star']
print(X_star.shape)

X_star[0:50]

(8990, 2)


array([[-15.    ,  -4.    ],
       [-14.5   ,  -4.    ],
       [-14.    ,  -4.    ],
       [-13.5   ,  -4.    ],
       [-13.    ,  -4.    ],
       [-12.5   ,  -4.    ],
       [-12.    ,  -4.    ],
       [-11.5   ,  -4.    ],
       [-11.    ,  -4.    ],
       [-10.5   ,  -4.    ],
       [-10.    ,  -4.    ],
       [-15.    ,  -4.    ],
       [-14.5   ,  -4.    ],
       [-14.    ,  -4.    ],
       [-13.5   ,  -4.    ],
       [-13.    ,  -4.    ],
       [-12.5   ,  -4.    ],
       [-12.    ,  -4.    ],
       [-11.5   ,  -4.    ],
       [-11.    ,  -4.    ],
       [-10.5   ,  -4.    ],
       [-10.    ,  -4.    ],
       [-15.    ,  -3.7333],
       [-14.5   ,  -3.7333],
       [-14.    ,  -3.7333],
       [-13.5   ,  -3.7333],
       [-13.    ,  -3.7333],
       [-12.5   ,  -3.7333],
       [-12.    ,  -3.7333],
       [-11.5   ,  -3.7333],
       [-11.    ,  -3.7333],
       [-10.5   ,  -3.7333],
       [-10.    ,  -3.7333],
       [-15.    ,  -3.7333],
       [-14.5 

In [17]:
t = data['t']
print(t.shape)

t

(149, 1)


array([[ 7599],
       [ 7748],
       [ 7897],
       [ 8046],
       [ 8195],
       [ 8344],
       [ 8493],
       [ 8642],
       [ 8791],
       [ 8940],
       [ 9089],
       [ 9238],
       [ 9387],
       [ 9536],
       [ 9685],
       [ 9834],
       [ 9983],
       [10132],
       [10281],
       [10430],
       [10579],
       [10728],
       [10877],
       [11026],
       [11175],
       [11324],
       [11473],
       [11622],
       [11771],
       [11920],
       [12069],
       [12218],
       [12367],
       [12516],
       [12665],
       [12814],
       [12963],
       [13112],
       [13261],
       [13410],
       [13559],
       [13708],
       [13857],
       [14006],
       [14155],
       [14304],
       [14453],
       [14602],
       [14751],
       [14900],
       [15049],
       [15198],
       [15347],
       [15496],
       [15645],
       [15794],
       [15943],
       [16092],
       [16241],
       [16390],
       [16539],
       [16688],
       [

In [18]:
u_star = data['U_star']
print(u_star.shape)

u_star

(8990, 2, 149)


array([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 5.0000e-01,  5.0000e-01,  5.0000e-01, ...,  5.0000e-01,
          5.0000e-01,  5.0000e-01]],

       [[ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       ...,

       [[ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e

In [19]:
p = data['p_star']
print(p.shape)
p

(8990, 149)


array([[ 4.7570e-01,  4.7604e-01,  4.7641e-01, ...,  4.6887e-01,
         4.6886e-01,  4.6855e-01],
       [ 4.3424e-01,  4.3459e-01,  4.3496e-01, ...,  4.2742e-01,
         4.2741e-01,  4.2710e-01],
       [ 3.8623e-01,  3.8658e-01,  3.8695e-01, ...,  3.7940e-01,
         3.7940e-01,  3.7909e-01],
       ...,
       [ 1.1180e-03,  1.0696e-03,  1.0646e-03, ..., -7.8991e-04,
         1.4163e-03,  3.3725e-03],
       [ 5.6183e-04,  5.1522e-04,  4.8151e-04, ..., -4.4073e-04,
         3.9453e-04,  1.1819e-03],
       [ 8.6097e-05,  5.9218e-05,  2.9522e-05, ..., -6.3989e-05,
        -1.1308e-04, -1.8871e-04]])